build:
    image: docker:28
    stage: build
    needs:
        -   job: define-version-app
            artifacts: true
    before_script:
        - echo "🔑 Connexion au registre Docker"
        - echo "$CI_REGISTRY_PASSWORD" | docker login "$CI_REGISTRY" -u "$CI_REGISTRY_USER" --password-stdin
    script:
        - echo "🏗️ Build du projet ($APP_VERSION)"
        - docker build  --build-arg APP_VERSION="$APP_VERSION" --target frankenphp_prod  -t "$CI_REGISTRY_IMAGE:$APP_VERSION" . --no-cache
        - docker push "$CI_REGISTRY_IMAGE:$APP_VERSION"
        - docker tag "$CI_REGISTRY_IMAGE:$APP_VERSION" "$CI_REGISTRY_IMAGE:$TAG"
        - docker push "$CI_REGISTRY_IMAGE:$TAG"
        # Tag supplémentaire unique par pipeline pour aligner npm/composer si besoin
        - echo "🔖 Tag unique SDK_VERSION=$SDK_VERSION"
        - docker tag "$CI_REGISTRY_IMAGE:$APP_VERSION" "$CI_REGISTRY_IMAGE:$SDK_VERSION"
        - docker push "$CI_REGISTRY_IMAGE:$SDK_VERSION"
