release-production:
    stage: release
    needs:
        -   job: build
        -   job: define-version-app
            artifacts: true
    rules:
        - !reference [ .rules_prod_branch, rules ]
    script:
        - echo "=== Installation gitlab release  ==="
        - apk add --no-cache curl
        - |
            curl -L -o /usr/local/bin/release-cli \
              "https://gitlab.com/api/v4/projects/gitlab-org%2Frelease-cli/packages/generic/release-cli/latest/release-cli-linux-amd64"
        - chmod +x /usr/local/bin/release-cli
        - |
            ASSETS_JSON="{\"name\":\"$CI_REGISTRY_IMAGE:$APP_VERSION\",\"url\":\"https://$CI_REGISTRY_IMAGE:$APP_VERSION\",\"type\":\"image\"}"
            release-cli create \
              --name "Release $APP_VERSION" \
              --tag-name "$APP_VERSION" \
              --ref "$CI_COMMIT_SHA" \
              --assets-link "$ASSETS_JSON"
    environment:
        name: production
