.rules_mr_dev:
    rules:
        -   if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'
            variables:
                TAG: "rc"
            when: on_success

.rules_other_branch:
    rules:
        -   if: '$CI_COMMIT_BRANCH != "dev" && $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH'
            variables:
                TAG: "sandbox"
            when: on_success

.rules_dev_branch:
    rules:
        -   if: '$CI_COMMIT_BRANCH == "dev"'
            variables:
                TAG: "nightly"
            when: on_success

.rules_prod_branch:
    rules:
        -   if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
            variables:
                TAG: "latest"
